using Biohazrd.OutputGeneration.Tests;
using Biohazrd.Tests.Common;
using System;
using Xunit;

namespace Biohazrd.CSharp.Tests
{
    public sealed class CSharpCodeWriterTests : BiohazrdCodeWriterTestBase<CSharpCodeWriter>
    {
        private const string AutoGeneratedPrefix = "// <auto-generated />\n#nullable enable\n";

        [Fact]
        [RelatedIssue("https://github.com/InfectedLibraries/Biohazrd/issues/149")]
        public void HeaderComment()
        {
            CodeWriterTest
            (
@"// <auto-generated>
// GENERATED
// FILE
// </auto-generated>
#nullable enable
using System;

Console.WriteLine(""Hello, world!"");
",
                session => session.GeneratedFileHeader = "GENERATED\nFILE",
                writer =>
                {
                    writer.Using("System"); // Console
                    writer.WriteLine(@"Console.WriteLine(""Hello, world!"");");
                }
            );
        }

        [Fact]
        [RelatedIssue("https://github.com/InfectedLibraries/Biohazrd/issues/149")]
        public void AutoGeneratedEvenWithoutHeaderComment()
        {
            CodeWriterTest
            (
@"// <auto-generated />
#nullable enable
",
                writer => { }
            );
        }

        [Fact]
        public void Using()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using System;

Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using("System"); // Intentionally add the using after writing code to show it goes to the top of the file
                }
            );
        }

        [Fact]
        public void UsingsAreSorted()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using A;
using B;
using C;

Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using("B");
                    writer.Using("C");
                    writer.Using("A");
                }
            );
        }

        [Fact]
        public void UsingsAreDeduplicated()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using Test1;
using Test2;

Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using("Test1");
                    writer.Using("Test2");

                    writer.Using("Test1");
                    writer.Using("Test2");
                }
            );
        }

        [Fact]
        public void UsingsDeduplicationIsCaseSensitive()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
// You might expect this to be Test1, TEST1, Test2 TEST2 if you expected ordinal sorting, but we use InvariantCulture which apparently sorts this way.
// This is consistent with Visual Studio's "Remove and Sort Usings" feature, so I think this is reasonable.
@"using Test1;
using TEST1;
using Test2;
using TEST2;

Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using("Test1");
                    writer.Using("Test2");
                    writer.Using("TEST1");
                    writer.Using("TEST2");

                    writer.Using("Test1");
                    writer.Using("Test2");
                    writer.Using("TEST1");
                    writer.Using("TEST2");
                }
            );
        }

        [Fact]
        public void UsingIsSanitized()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using System;
using Terrible.@namespace.Name;

Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using("System");
                    writer.Using("Terrible.namespace.Name");
                }
            );
        }

        [Fact]
        public void UsingNullDoesNothing()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"Console.WriteLine(""Hello, world!"");
",
                writer =>
                {
                    writer.WriteLine("Console.WriteLine(\"Hello, world!\");");
                    writer.Using(null);
                }
            );
        }

        [Fact]
        public void UsingEmptyStringIsError()
        {
            FillCodeWriterAndGetCode
            (
                writer =>
                {
                    ArgumentException ex = Assert.Throws<ArgumentException>(() => writer.Using(String.Empty));
                    Assert.Equal("fullNamespaceName", ex.ParamName);
                    Assert.Contains("must not be empt", ex.Message);
                }
            );
        }

        [Fact]
        public void DisableScope()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
// The extra newline after LINE1 may seem odd, but the DisabledScope ensures separation since it's intended to be used to disable a declaration
@"LINE1

#if false
DISABLED1
DISABLED2
#endif
LINE2
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    using (writer.DisableScope())
                    {
                        writer.EnsureSeparation(); // This is expected to do nothing since we're "part" of the disabled block
                        writer.WriteLine("DISABLED1");
                        writer.WriteLine("DISABLED2");
                    }
                    writer.WriteLine("LINE2");
                }
            );
        }

        [Fact]
        public void DisableScope_NoSeparation()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"LINE1
#if false
DISABLED1
DISABLED2
#endif
LINE2
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    writer.NoSeparationNeededBeforeNextLine();
                    using (writer.DisableScope())
                    {
                        writer.EnsureSeparation(); // This is expected to do nothing since we're "part" of the disabled block
                        writer.WriteLine("DISABLED1");
                        writer.WriteLine("DISABLED2");
                    }
                    writer.WriteLine("LINE2");
                }
            );
        }

        [Fact]
        public void DisableScope_Message()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"LINE1

#if false // MESSAGE
DISABLED1
DISABLED2
#endif
LINE2
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    using (writer.DisableScope("MESSAGE"))
                    {
                        writer.WriteLine("DISABLED1");
                        writer.WriteLine("DISABLED2");
                    }
                    writer.WriteLine("LINE2");
                }
            );
        }

        [Fact]
        public void DisableScope_Indented()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"LINE1
    LINE2

#if false // MESSAGE
    DISABLED1
    DISABLED2
#endif
    LINE3
LINE4
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    using (writer.Indent())
                    {
                        writer.WriteLine("LINE2");
                        using (writer.DisableScope("MESSAGE"))
                        {
                            writer.WriteLine("DISABLED1");
                            writer.WriteLine("DISABLED2");
                        }
                        writer.WriteLine("LINE3");
                    }
                    writer.WriteLine("LINE4");
                }
            );
        }

        [Fact]
        public void DisableScope_NoDisable()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"LINE1
DISABLED1
DISABLED2
LINE2
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    using (writer.DisableScope(false, "MESSAGE"))
                    {
                        writer.WriteLine("DISABLED1");
                        writer.WriteLine("DISABLED2");
                    }
                    writer.WriteLine("LINE2");
                }
            );
        }

        [Fact]
        public void DisableScope_NoDisableEnsureSeparation()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"LINE1

DISABLED1
DISABLED2
LINE2
",
                writer =>
                {
                    writer.WriteLine("LINE1");
                    using (writer.DisableScope(false, "MESSAGE"))
                    {
                        writer.EnsureSeparation();
                        writer.WriteLine("DISABLED1");
                        writer.WriteLine("DISABLED2");
                    }
                    writer.WriteLine("LINE2");
                }
            );
        }

        [Fact]
        public void WriteIdentifier_Basic()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix + "MyClass",
                writer => writer.WriteIdentifier("MyClass")
            );
        }

        [Fact]
        public void WriteIdentifier_Keyword()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix + "@class",
                writer => writer.WriteIdentifier("class")
            );
        }

        [Fact]
        public void WriteIdentifier_IllegalCharacter()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix + "MyClass__UNICODE_0021__",
                writer => writer.WriteIdentifier("MyClass!")
            );
        }

        [Fact]
        public void SanitizeIdentifier_Basic()
            => Assert.Equal("MyClass", CSharpCodeWriter.SanitizeIdentifier("MyClass"));

        [Fact]
        public void SanitizeIdentifier_Keyword()
        {
            Assert.Equal("@class", CSharpCodeWriter.SanitizeIdentifier("class"));
            Assert.Equal("@if", CSharpCodeWriter.SanitizeIdentifier("if"));
            Assert.Equal("@virtual", CSharpCodeWriter.SanitizeIdentifier("virtual"));
            Assert.Equal("@namespace", CSharpCodeWriter.SanitizeIdentifier("namespace"));
            Assert.Equal("@in", CSharpCodeWriter.SanitizeIdentifier("in"));
        }

        [Fact]
        public void SanitizeIdentifier_IllegalCharacters()
            => Assert.Equal("MyClass__UNICODE_003F__", CSharpCodeWriter.SanitizeIdentifier("MyClass?"));

        [Fact]
        public void IsLegalIdentifier_Basic()
            => Assert.True(CSharpCodeWriter.IsLegalIdentifier("MyClass"));

        [Fact]
        public void IsLegalIdentifier_Keyword()
            // Keywords are considered legal since they can be written out in a sensible manner
            => Assert.True(CSharpCodeWriter.IsLegalIdentifier("class"));

        [Fact]
        public void IsLegalIdentifier_IllegalCharacters()
            => Assert.False(CSharpCodeWriter.IsLegalIdentifier("MyClass?"));

        [Fact]
        public void SanitizeNamespace_Basic()
            => Assert.Equal("MyNamespace", CSharpCodeWriter.SanitizeNamespace("MyNamespace"));

        [Fact]
        public void SanitizeNamespace_Keyword()
            => Assert.Equal("@namespace", CSharpCodeWriter.SanitizeNamespace("namespace"));

        [Fact]
        public void SanitizeNamespace_IllegalCharacters()
            => Assert.Equal("My__UNICODE_0020__Namespace", CSharpCodeWriter.SanitizeNamespace("My Namespace"));

        [Fact]
        public void SanitizeNamespace_NestedBasic()
            => Assert.Equal("MyNamespace.SubNamespace", CSharpCodeWriter.SanitizeNamespace("MyNamespace.SubNamespace"));

        [Fact]
        public void SanitizeNamespace_NestedKeyword()
            => Assert.Equal("@class.@namespace", CSharpCodeWriter.SanitizeNamespace("class.namespace"));

        [Fact]
        public void SanitizeNamespace_NestedIllegalCharacters()
            => Assert.Equal("My__UNICODE_0020__Namespace.SubNamespace__UNICODE_003F__", CSharpCodeWriter.SanitizeNamespace("My Namespace.SubNamespace?"));

        [Fact]
        public void SanitizeNamespace_Everything()
            => Assert.Equal("My__UNICODE_0020__Namespace.@namespace.SubNamespace__UNICODE_003F__.@class.Cool", CSharpCodeWriter.SanitizeNamespace("My Namespace.namespace.SubNamespace?.class.Cool"));

        [Fact]
        public void SanitizeStringLiteral_Basic()
            => Assert.Equal("Hello, world!", CSharpCodeWriter.SanitizeStringLiteral("Hello, world!"));

        [Fact]
        public void SanitizeStringLiteral_EmbeddedQuote()
            => Assert.Equal(@"Hello, \""world\""!", CSharpCodeWriter.SanitizeStringLiteral("Hello, \"world\"!"));

        [Fact]
        public void SanitizeStringLiteral_Backslash()
            => Assert.Equal(@"Hello You\\World!", CSharpCodeWriter.SanitizeStringLiteral("Hello You\\World!"));

        [Fact]
        public void SanitizeStringLiteral_WellKnownUnprintables()
            => Assert.Equal(@"\0\a\b\f\t\v", CSharpCodeWriter.SanitizeStringLiteral("\0\a\b\f\t\v"));

        [Fact]
        public void SanitizeStringLiteral_LineTerminators()
            => Assert.Equal(@"\r\n\x0085\x2028\x2029", CSharpCodeWriter.SanitizeStringLiteral("\r\n\x0085\x2028\x2029"));

        [Fact]
        public void SanitizeStringLiteral_AnnoyingToPrint()
        {
            // None of these strictly have to be escape as per the C# spec, but they tend to be problematic to have embedded directly in code
            // because they don't render in all editors or they're invisible by nature.

            // ZERO WIDTH SPACE
            Assert.Equal(@"\x200B", CSharpCodeWriter.SanitizeStringLiteral("\u200B"));

            // Private Use, First
            Assert.Equal(@"\xE000", CSharpCodeWriter.SanitizeStringLiteral("\uE000"));

            // Plane 16 Private Use, First
            Assert.Equal(@"\xDBC0\xDC00", CSharpCodeWriter.SanitizeStringLiteral("\uDBC0\uDC00"));

            // WOMAN + EMOJI MODIFIER FITZPATRICK TYPE-5 + ZERO WIDTH JOINER + PERSONAL COMPUTER = The woman technologist emoji with medium-dark skin
            Assert.Equal(@"\xD83D\xDC69\xD83C\xDFFE\x200D\xD83D\xDCBB", CSharpCodeWriter.SanitizeStringLiteral("\uD83D\uDC69\uD83C\uDFFE\u200D\uD83D\uDCBB"));
        }

        [Fact]
        public void SanitizeMulitlineComment_NothingToDo()
            => Assert.Equal("Hello, world!", CSharpCodeWriter.SanitizeMultiLineComment("Hello, world!"));

        [Fact]
        public void SanitizeMulitlineComment_CommentWithin()
            /* C# provides no real means for escaping a multi-line comment within a multi-line comment
             * This helper function is proided purely for robustness purposes. In the rare case a string that will be written as a multi-line comment contains a *​/
             * we need to do something about it. The something we do is that we insert a zero-width space to "break" the end of the multi-line comment.         (^__Just like this)
             * This is generally invisible to developers looking at the code in an editor and allows the code to still compile.
             */
            => Assert.Equal("Hello, /* Test *\x200B/ world!", CSharpCodeWriter.SanitizeMultiLineComment("Hello, /* Test */ world!"));

        [Fact]
        public void Namespace_Basic()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.EnsureSeparation(); // There should be no separation after the opening of a block
                        writer.WriteLine("// Code");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_BasicTwoLevel()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace.SubNamespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace.SubNamespace"))
                    {
                        writer.WriteLine("// Code");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_Nested()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
    namespace SubNamespace
    {
        // SubCode
    }
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                        writer.NoSeparationNeededBeforeNextLine();
                        using (writer.Namespace("MyNamespace.SubNamespace"))
                        {
                            writer.WriteLine("// SubCode");
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NestedTwoLevel()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace.SubNamespace
{
    // Code
    namespace SubSubNamespace.SubSubSubNamespace
    {
        // SubCode
    }
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace.SubNamespace"))
                    {
                        writer.WriteLine("// Code");
                        writer.NoSeparationNeededBeforeNextLine();
                        using (writer.Namespace("MyNamespace.SubNamespace.SubSubNamespace.SubSubSubNamespace"))
                        {
                            writer.WriteLine("// SubCode");
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NestedIllegal1()
        {
            FillCodeWriterAndGetCode
            (
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        ArgumentException ex = Assert.Throws<ArgumentException>(() => writer.Namespace("OtherNamespace.SubNamespace"));
                        Assert.Contains("is not a child of the current namespace", ex.Message);
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NestedIllegal2()
        {
            FillCodeWriterAndGetCode
            (
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        // This tests that the namespace match isn't a dumb StartsWith match
                        ArgumentException ex = Assert.Throws<ArgumentException>(() => writer.Namespace("MyNamespaceJustKidding.SubNamespace"));
                        Assert.Contains("is not a child of the current namespace", ex.Message);
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NoChange()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code

    // MoreCode
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.EnsureSeparation();
                        writer.WriteLine("// Code");

                        using (writer.Namespace("MyNamespace"))
                        {
                            writer.EnsureSeparation();
                            writer.WriteLine("// MoreCode");
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_IsInNamespaceOrRoot()
        {
            FillCodeWriterAndGetCode
            (
                writer =>
                {
                    Assert.True(writer.IsInNamespaceOrRoot);
                    using (writer.Namespace("MyNamespace"))
                    {
                        Assert.True(writer.IsInNamespaceOrRoot);
                        writer.EnsureSeparation();
                        writer.WriteLine("// Code");

                        using (writer.Namespace("MyNamespace.SubNamespace"))
                        {
                            Assert.True(writer.IsInNamespaceOrRoot);
                            writer.EnsureSeparation();
                            writer.WriteLine("// MoreCode");
                            using (writer.Block())
                            {
                                Assert.False(writer.IsInNamespaceOrRoot);
                                writer.WriteLine("// InsideBlock");
                            }
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NonsenicalNamespaceChange()
        {
            FillCodeWriterAndGetCode
            (
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        using (writer.Block())
                        {
                            // A namespace can't be created within this scope because we're inside a block
                            InvalidOperationException ex = Assert.Throws<InvalidOperationException>(() => writer.Namespace("MyNamespace.IllegalNamespace"));
                            Assert.Contains("namespace cannot be changed", ex.Message); // Sanity that the exception is for the reason we expect
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_IsSanitized()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace @namespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("namespace"))
                    {
                        writer.WriteLine("// Code");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NothingOnNull()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"// Code
",
                writer =>
                {
                    using (writer.Namespace(null))
                    {
                        writer.WriteLine("// Code");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_NothingOnNullNested()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        using (writer.Namespace(null))
                        {
                            writer.WriteLine("// Code");
                        }
                    }
                }
            );
        }

        [Fact]
        public void Namespace_InScopeUsingIsDropped1()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using MyNamespace.OtherNamespace;
using System;

namespace MyNamespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                        writer.Using("System");
                        writer.Using("MyNamespace");
                        writer.Using("MyNamespace.OtherNamespace");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_InScopeUsingIsDropped2()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"using MyNamespace.OtherNamespace;
using MyNamespace.SubNamespace.OtherNamespace;
using System;

namespace MyNamespace.SubNamespace
{
    // Code
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace.SubNamespace"))
                    {
                        writer.WriteLine("// Code");
                        writer.Using("System");
                        writer.Using("MyNamespace");
                        writer.Using("MyNamespace.SubNamespace");
                        writer.Using("MyNamespace.SubNamespace.OtherNamespace");
                        writer.Using("MyNamespace.OtherNamespace");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_FollowedByAnother()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
}

namespace MyOtherNamespace
{
    // Code2
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                    }

                    using (writer.Namespace("MyOtherNamespace"))
                    {
                        writer.WriteLine("// Code2");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_Automerge1()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
    // Code2
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                    }

                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code2");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_Automerge2()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace.Nested
{
    // Code
    // Code2
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace.Nested"))
                    {
                        writer.WriteLine("// Code");
                    }

                    using (writer.Namespace("MyNamespace.Nested"))
                    {
                        writer.WriteLine("// Code2");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_AutomergeNested()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code

    namespace Nested
    {
        // NestedCode
        // Code2
    }
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                        using (writer.Namespace("MyNamespace.Nested"))
                        {
                            writer.WriteLine("// NestedCode");
                        }
                    }

                    using (writer.Namespace("MyNamespace.Nested"))
                    {
                        writer.WriteLine("// Code2");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_AutomergeNestedPartialMatch()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code

    namespace Nested
    {
        // NestedCode
    }

    namespace Nested2
    {
        // NestedCode2
    }
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                        using (writer.Namespace("MyNamespace.Nested"))
                        {
                            writer.WriteLine("// NestedCode");
                        }
                    }

                    using (writer.Namespace("MyNamespace.Nested2"))
                    {
                        writer.WriteLine("// NestedCode2");
                    }
                }
            );
        }

        [Fact]
        public void Namespace_AutomergeInterrupted()
        {
            CodeWriterTest
            (
                AutoGeneratedPrefix +
@"namespace MyNamespace
{
    // Code
}

// Interruption

namespace MyNamespace
{
    // Code2
}
",
                writer =>
                {
                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code");
                    }

                    writer.EnsureSeparation();
                    writer.WriteLine("// Interruption");

                    using (writer.Namespace("MyNamespace"))
                    {
                        writer.WriteLine("// Code2");
                    }
                }
            );
        }
    }
}
